// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBm4m_TOSdsQ9e-nEbn32eWRW1s6yNfbw4',
    appId: '1:227921679291:android:756d71ca4cec1e2a1caa9e',
    messagingSenderId: '227921679291',
    projectId: 'pushnotification-59b7c',
    databaseURL: 'https://pushnotification-59b7c-default-rtdb.firebaseio.com',
    storageBucket: 'pushnotification-59b7c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCV3ePuPPtEM4QhZXFL86WC3AZbOx4jJlU',
    appId: '1:227921679291:ios:1772a19445b4a6de1caa9e',
    messagingSenderId: '227921679291',
    projectId: 'pushnotification-59b7c',
    databaseURL: 'https://pushnotification-59b7c-default-rtdb.firebaseio.com',
    storageBucket: 'pushnotification-59b7c.appspot.com',
    iosClientId: '227921679291-cdcf3lghn4a9b5ppgrclm6h8ffk5fhe8.apps.googleusercontent.com',
    iosBundleId: 'com.example.pushNotification',
  );
}
